apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "api-deployment.fullname" . | trunc 50 | trimSuffix "-" }}-listener
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            labels:
              networking/traffic-allowed: "yes"
          spec:
            {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
  serviceAccountName: {{ include "api-deployment.fullname" . }}-tekton-sa
  triggers:
  - bindings:
    - ref: {{ include "api-deployment.fullname" . }}-api-trigger-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: secretToken
          secretName: {{ include "api-deployment.fullname" . }}-api-webhook-secret
      - name: eventTypes
        value:
        - registry_package
      ref:
        apiVersion: triggers.tekton.dev
        kind: ClusterInterceptor
        name: github
    name: api-trigger
    template:
      ref: {{ include "api-deployment.fullname" . }}-api-trigger-template