apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-webhook-secret
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
stringData:
  secretToken: {{ required "apiGithubWebhookSecret.secretToken is required" .Values.apiGithubWebhookSecret.secretToken
    | quote }}
type: Opaque