apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-trigger-template
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: registryUrl
  - name: chartName
  - name: chartVersion
  - name: namespace
  - name: helmChartPullType
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: api-pipeline-run-
      namespace: {{ .Release.Namespace }}
    spec:
      params:
      - name: action
        value: $(tt.body.action)
      - name: registryUrl
        value: $(tt.params.registryUrl)
      - name: chartName
        value: $(tt.params.chartName)
      - name: chartVersion
        value: $(tt.params.chartVersion)
      - name: namespace
        value: $(tt.params.namespace)
      - name: helmChartPullType
        value: $(tt.params.helmChartPullType)
      pipelineRef:
        name: {{ include "api-deployment.fullname" . }}-api-pipeline
      serviceAccountName: {{ include "api-deployment.fullname" . }}-tekton-sa
      podTemplate:
        {{- with .Values.tolerations }}
        tolerations:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
            {{- toYaml . | nindent 10 }}
        {{- end }}