apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-pipeline
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: registryUrl
    type: string
  - name: chartName
    type: string
  - name: chartVersion
    type: string
  - description: Namespace where the chart will be deployed
    name: namespace
    type: string
  - name: helmChartPullType
    type: string
  tasks:
  - name: tekton-task
    params:
    - name: registryUrl
      value: $(params.registryUrl)
    - name: chartName
      value: $(params.chartName)
    - name: chartVersion
      value: $(params.chartVersion)
    - name: namespace
      value: $(params.namespace)
    - name: helmChartPullType
      value: $(params.helmChartPullType)
    taskRef:
      name: {{ include "api-deployment.fullname" . }}-tekton-task