apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-docker-secret
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ required "ApiDockerSecret.dockerconfigjson is required"
    .Values.ApiDockerSecret.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfigjson