apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-trigger-binding
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: action
    value: $(body.action)
  - name: registryUrl
    value: {{ .Values.registryUrl }}
  - name: chartName
    value: {{ .Values.chartName }}
  - name: chartVersion
    value: {{ .Values.chartVersion }}
  - name: namespace
    value: {{ .Release.Namespace }}
  - name: helmChartPullType
    value: {{ .Values.helmChartPullType }}