apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-config
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.apiConfig.configYaml | toYaml | indent 1 }}