apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-docker-secret
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
{{- if .Values.apiDockerSecret.dockerconfigjson }}
data:
  .dockerconfigjson: {{ .Values.apiDockerSecret.dockerconfigjson | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
