apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "api-deployment.fullname" . }}-pipeline
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: helm-workspace
  params:
    - name: registryUrl
      type: string
    - name: chartName
      type: string
    - name: chartVersion
      type: string
    - name: namespace
      type: string
    - name: useOciRegistry
      type: string
    - name: webAppRepoUrl
      type: string
    - name: webAppRevision
      type: string
    - name: cypressBaseUrl
      type: string
    - name: authKeycloakRealm
      type: string
    - name: authKeycloakClientId
      type: string
    - name: authKeycloakClientSecret
      type: string
    - name: runCypressTests   # ➡️ New parameter to control Cypress execution
      type: string
      default: "false"
  tasks:
    - name: deploy-api
      params:
        - name: registryUrl
          value: $(params.registryUrl)
        - name: chartName
          value: $(params.chartName)
        - name: chartVersion
          value: $(params.chartVersion)
        - name: namespace
          value: $(params.namespace)
        - name: useOciRegistry
          value: $(params.useOciRegistry)
      taskRef:
        name: {{ include "api-deployment.fullname" . }}-tekton-task
      workspaces:  
        - name: helm-workspace
          workspace: helm-workspace  

    - name: run-cypress-tests
      runAfter:
        - deploy-api
      when:
        - input: $(params.runCypressTests)
          operator: in
          values: ["true"]  # ➡️ Runs only if `runCypressTests` is "true"
      params:
        - name: webAppRepoUrl
          value: $(params.webAppRepoUrl)
        - name: webAppRevision
          value: $(params.webAppRevision)
        - name: cypressBaseUrl
          value: $(params.cypressBaseUrl)
        - name: authKeycloakRealm
          value: $(params.authKeycloakRealm)
        - name: authKeycloakClientId
          value: $(params.authKeycloakClientId)
        - name: authKeycloakClientSecret
          value: $(params.authKeycloakClientSecret)
      taskRef:
        name: {{ include "api-deployment.fullname" . }}-cypress-tests
