apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "api-deployment.fullname" . }}-api-trigger-template
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: registry_url
  - name: chart_name
  - name: chart_version
  - name: namespace
  - name: helm_chart_pull_type
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: api-pipeline-run-
      namespace: {{ .Release.Namespace }}
    spec:
      params:
      - name: action
        value: $(tt.body.action)
      - name: registry_url
        value: $(tt.params.registry_url)
      - name: chart_name
        value: $(tt.params.chart_name)
      - name: chart_version
        value: $(tt.params.chart_version)
      - name: namespace
        value: $(tt.params.namespace)
      - name: helm_chart_pull_type
        value: $(tt.helm_chart_pull_type)
      pipelineRef:
        name: {{ include "api-deployment.fullname" . }}-api-pipeline
      serviceAccountName: {{ include "api-deployment.fullname" . }}-tekton-sa
      podTemplate:
        {{- with .Values.tolerations }}
        tolerations:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
            {{- toYaml . | nindent 10 }}
        {{- end }}