apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-deployment.fullname" . }}-tekton-sa
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.tektonSa.serviceAccount.annotations | nindent 4 }}