apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api-deployment.fullname" . }}-tekton-role-binding-k8s
  labels:
  {{- include "api-deployment.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "api-deployment.fullname" . }}-tekton-role-k8s'
subjects:
- kind: ServiceAccount
  name: '{{ include "api-deployment.fullname" . }}-tekton-sa'
  namespace: '{{ .Release.Namespace }}'